spring:
  jackson:
    time-zone: Europe/Stockholm
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  application:
    name: kma_backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
app:
  admin-email: ${ADMIN_EMAIL}

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_KEY}
  api-secret: ${CLOUD_SECRET}


logging:
  level:
    org.hibernate.SQL: DEBUG         # Loggar SQL-satser
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
